//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosen
    {
        public int DosenId { get; set; }
        public Nullable<long> Nidn { get; set; }
        public string DosenName { get; set; }
        public string Prodi { get; set; }
        public string MailID { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
